### ISSUE TITLE
Fluentd Elasticsearch output stops sending data

### ISSUE THREAD

**Issue by yusufcan141** [tagomoris/fluent-plugin-forest#18]
I'm using elasticsearch output. Every morning at 6.30, all machines stop sending data to elasticsearch and S3. I'm using fluent-plugin-forest also. Here is the error:

2015-05-14 20:05:14 +0300 [error]: Cannot output messages with tag 'elasticsearch.esData.events_2015_05_01.file.log'
2015-05-14 20:05:14 +0300 [error]: failed to configure/start sub output elasticsearch: can't create Thread: Resource temporarily unavailable
2015-05-14 20:05:14 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:110:in initialize' /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:110:innew'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:110:in start' /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:237:inblock in start'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:237:in each' /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:237:instart'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-0.8.0/lib/fluent/plugin/out_elasticsearch.rb:44:in start' /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-forest-0.3.0/lib/fluent/plugin/out_forest.rb:133:inblock in plant'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-forest-0.3.0/lib/fluent/plugin/out_forest.rb:128:in synchronize' /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-forest-0.3.0/lib/fluent/plugin/out_forest.rb:128:inplant'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-forest-0.3.0/lib/fluent/plugin/out_forest.rb:168:in emit' /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:32:innext'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/buffer.rb:184:in block in emit' /opt/td-agent/embedded/lib/ruby/2.1.0/monitor.rb:211:inmon_synchronize'

**Comment by tagomoris** [comment]
I saw fluent/fluentd#596. Many tags requires many memory and more cpu power.
Use more powerful machine, or decrease number of tags.

**Comment by yusufcan141** [comment]
Ok thanks but do you have any idea why it stops at same time everyday?

**Comment by tagomoris** [comment]
I don't know exact reason for that, but I assume that your ruby process for fluentd may grow until crash at 6:30 every morning...

**Comment by yusufcan141** [comment]
Ok thanks
