### ISSUE TITLE
Buffered output doesn't work since 0.14

### ISSUE THREAD

**Issue by njam** [tagomoris/fluent-plugin-forest#32]
Since fluentd 0.14 I can't make buffered outputs in a forest work anymore.

With a simple configuration like this:
```
<match **>
  @type forest
  subtype file
  <template>
    path /tmp/foo-__TAG__
    buffer_type memory
    flush_interval 1s
  </template>
</match>
```

It seems buffers aren't flushed anymore.
(all works fine in a *non-buffered* configuration, and the buffered version works fine without *forest*)

I'm running the latest fluentd 0.14.6 and fluent-plugin-forest 0.3.1.

**Comment by jottos** [comment]
I have exact same issue as @njam 

What we are noticing is that on the inbound the buffer files are all being created along with their *.meta files BUT none of the buffered files are being drained to their respective output plugins. So far we have only been able to track the problem to the file_chunk.rb which sends errors like this to the td-agent.log file

**Comment by tagomoris** [comment]
As far as I tested, i reproduced this problem, but no `Errono::ENOENT` error raised.

```apache
<source>
  @type dummy
  tag test.dummy
  dummy {"message":"yaaaaaaaaaaaaay"}
  rate 3
</source>

<match test.*>
  @type forest
  subtype file
  <template>
    path /tmp/file_${tag}
    buffer_type file
    flush_interval 1s
  </template>
</match>
```

**Comment by tagomoris** [comment]
I found the root cause. Fluentd v0.14.6 introduced a new lifecycle control via `#after_start` method.
But fluent-plugin-forest doesn't call it.

**Comment by tagomoris** [comment]
I just released v0.3.2 to solve this problem. Thank you for reporting!

**Comment by jottos** [comment]
Thank you, Satoshi. I will test in the morning.
/jos

**Comment by njam** [comment]
Thank you! works for me! 🚲
