### ISSUE TITLE
log data dropping when using Fuentd

### ISSUE THREAD

**Issue by woosanwoosang** [tagomoris/fluent-plugin-forest#34]
Hello,
when using Fuentd, I have encountered that with AWS ELB, log data from server seemed to be dropped.
Unfortunately I do not have log data remaining and fluentd server did not generate its own log data.
I know there’s not much data you can refer to, but can you please let me know if there’s something to leave a comment about the architecture or case study from others?
my AWS ELB did not have any error log.
 
The past architecture : 
server -> ELB -> fluentd server -> public network enhancer -> on-premise 
it showed daily 5%~10% log data dropping
 
the new architecture :
server  -> fluentd server -> public network enhancer -> on-premise 
and/or 
game server  -> public network enhancer -> on-premise 
it showed 0% log data dropping
 
thanks

**Comment by tagomoris** [comment]
Is it troubleshooting just about AWS ELB?
It's not about this plugin. Could you go to Fluentd ML or StackOverflow?

**Comment by woosanwoosang** [comment]
thanks for recommnedation
