### ISSUE TITLE
Could you please provide the sample for fluentd v0.14

### ISSUE THREAD

**Issue by mikeshi80** [tagomoris/fluent-plugin-forest#35]
Firstly thank you for the amazing plugin.

Currently, I upgrade fluentd to v0.14 because I want to use nanosecond precision. And I found the plugin README says: NOTE: This plugin will not be updated: Use Fluentd v0.14 native API to handle tags.

As what I understood, the plugin is not required if I use v0.14? Where can I find the instruction about tag usage in v0.14?

**Comment by tagomoris** [comment]
The Fluentd v0.14 plugin APIs provide support to handle/inject many tags using just 1 instance of plugin - output plugins can inject tag strings into configuration values when it flushes buffers - *if that plugin is working on v0.14 APIs*.

That feature was originally introduced at release note, and then some documents (for Fluentd v0.14) have mentions about it.
* http://www.fluentd.org/blog/fluentd-v0.14.9-has-been-released
* http://docs.fluentd.org/v0.14/articles/output-plugin-overview#difference-between-v014-and-v012

**Comment by mikeshi80** [comment]
I tried as that mentioned in `fluentd-v0.14.9` release notes,

```
<source>
  @type forward
  port 24230
</source>
<match test.*>
  @type file
  path /var/log/td-agent/%Y/%m/%d/${tag}/mylog
  time_as_integer false
  append true
  <buffer time,tag>
    flush_at_shutdown true
  </buffer>
</match>
```

But I got the result as below:

```
.
└── %Y
    └── %m
        └── %d
            └── ${tag}
                └── mylog
                    ├── buffer.b54d3f82ad6e4809c38f377774df4700b.log
                    └── buffer.b54d3f82ad6e4809c38f377774df4700b.log.meta
```

What's wrong with the configuration?

And I am using `v.0.14.11`, with latest fluent-logger-python plugin, and send the logs by fluent.handler

**Comment by tagomoris** [comment]
The files you show are buffer chunk files, not files of output of `out_file` plugin.
Buffer plugin doesn't expand `${tag}` and timestamp placeholders.

But anyway, it's issue about Fluentd core, not fluent-plugin-forest.

**Comment by mikeshi80** [comment]
Thank you for your answer, I will study fluentd core.
